SAVEPATH:  runs_evaluation/callhome_eng.pt
Load Model...
From state-dict:  exp/callhome_eng.pt
########################################
Load pretrained CPC
########################################
Froze EncoderCPC!
Traceback (most recent call last):
  File "/data/group1/z40351r/VoiceActivityProjection/vap/evaluation.py", line 370, in <module>
    evaluate()
  File "/data/group1/z40351r/VoiceActivityProjection/vap/evaluation.py", line 272, in evaluate
    sd = torch.load(args.state_dict)
  File "/home/z40351r/anaconda3/envs/vap2/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/z40351r/anaconda3/envs/vap2/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/z40351r/anaconda3/envs/vap2/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'exp/callhome_eng.pt'
